# Generated by Django 5.0.1 on 2024-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='user_picture',
            field=models.ImageField(blank=True, default='idk', upload_to='users_picture'),
            preserve_default=False,
        ),
    ]
