# Generated by Django 5.0.1 on 2024-03-17 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_createuser_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
