# Generated by Django 5.0.1 on 2024-03-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_createuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='friends',
        ),
    ]
