# Generated by Django 5.0.1 on 2024-03-17 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_createuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
