# Generated by Django 5.0.1 on 2024-04-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_alter_createuser_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='createuser',
            name='conversations',
            field=models.ManyToManyField(blank=True, to='signup.conversation'),
        ),
    ]
