# Generated by Django 5.0.1 on 2024-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_remove_createuser_conversations_conversation_friend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.AddField(
            model_name='createuser',
            name='conversations',
            field=models.ManyToManyField(blank=True, to='signup.conversation'),
        ),
    ]
