# Generated by Django 5.0.1 on 2024-04-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_remove_conversation_friend_remove_conversation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='whoConversate',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
