# Generated by Django 5.0.1 on 2024-04-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_conversation_alter_messages_conversation'),
        ('signup', '0010_conversation_whoconversate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='conversations',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
