# Generated by Django 5.0.1 on 2024-04-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
    ]
