# Generated by Django 5.0.1 on 2024-04-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_remove_conversation_friend_remove_conversation_user'),
        ('signup', '0007_conversation_createuser_conversations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='signup.conversation'),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
