# Generated by Django 5.0.1 on 2024-06-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0006_alter_messages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_sent'),
        ),
    ]
