# Generated by Django 5.0.1 on 2024-06-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0007_alter_messages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
