# Generated by Django 5.2.5 on 2026-02-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0008_messages_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
